---
# ResourceClass that defines the blueprint for how a "standard" Azure PostgreSQL Server
# should be dynamically provisioned
apiVersion: database.azure.crossplane.io/v1alpha2
kind: SQLServerClass
metadata:
  name: sqlserverpostgresql
  namespace: crossplane-system
specTemplate:
  adminLoginName: myadmin
  resourceGroupName: group-westus-1
  location: West US
  sslEnforced: false
  version: "9.6"
  pricingTier:
    tier: Basic
    vcores: 1
    family: Gen5
  storageProfile:
    storageGB: 25
    backupRetentionDays: 7
    geoRedundantBackup: false
  providerRef:
    name: example
    namespace: crossplane-system
  reclaimPolicy: Delete
