---
apiVersion: database.crossplane.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: sqlserverpostgresql
spec:
  classRef:
    kind: SQLServerClass
    apiVersion: database.azure.crossplane.io/v1alpha2
    name: sqlserverpostgresql
    namespace: crossplane-system
  writeConnectionSecretToRef:
    name: sqlserverpostgres
  engineVersion: "9.6"
