---
apiVersion: database.crossplane.io/v1alpha1
kind: MySQLInstance
metadata:
  name: sqlservermysql
spec:
  classRef:
    kind: SQLServerClass
    apiVersion: database.azure.crossplane.io/v1alpha2
    name: sqlservermysql
    namespace: crossplane-system
  writeConnectionSecretToRef:
    name: sqlservermysql
  engineVersion: "5.6"
