# ResourceClass that defines the blueprint for how a "standard" CloudSQL instance
# should be dynamically provisioned
apiVersion: database.gcp.crossplane.io/v1alpha1
kind: CloudsqlInstanceClass
metadata:
  name: cloudsqlinstancepostgresql
  namespace: crossplane-system
specTemplate:
  databaseVersion: POSTGRES_9_6
  tier: db-custom-1-3840
  region: us-west2
  storageType: PD_SSD
  storageGB: 10
  providerRef:
    name: example
    namespace: crossplane-system
  reclaimPolicy: Delete
