apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: demo-cluster
  namespace: default
spec:
  classReference:
    name: standard-cluster
    namespace: crossplane-system
