# ResourceClass that defines the blueprint for how a "standard" GCP bucket
# should be dynamically provisioned
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: gcsbucket
  namespace: crossplane-system
parameters:
  location: US
  storageClass: MULTI_REGIONAL
provisioner: bucket.storage.gcp.crossplane.io/v1alpha1
providerReference:
  name: example
  namespace: crossplane-system
reclaimPolicy: Delete
