# ResourceClass that defines the blueprint for how a "standard" GCP bucket
# should be dynamically provisioned
apiVersion: storage.gcp.crossplane.io/v1alpha1
kind: BucketClass
metadata:
  name: gcsbucket
  namespace: crossplane-system
specTemplate:
  location: US
  storageClass: MULTI_REGIONAL
  providerRef:
    name: example
    namespace: crossplane-system
  reclaimPolicy: Delete
