---
apiVersion: storage.crossplane.io/v1alpha1
kind: MySQLInstance
metadata:
  name: rdsmysql
spec:
  classReference:
    name: rdsmysql
    namespace: crossplane-system
  writeConnectionSecretTo:
    name: rdsmysql
  engineVersion: "5.6"
