---
# ResourceClass that defines the blueprint for how a "standard" aws bucket
# should be dynamically provisioned
apiVersion: storage.aws.crossplane.io/v1alpha2
kind: S3BucketClass
metadata:
  name: standard-aws-bucket
  annotations:
    resource: bucket.storage.crossplane.io/v1alpha1
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  versioning: false
  cannedACL: private
  localPermission: ReadWrite
  region: REGION
  providerRef:
    name: demo-aws
  reclaimPolicy: Delete
