---
apiVersion: storage.aws.crossplane.io/v1alpha1
kind: S3BucketClass
metadata:
  name: s3bucket
  namespace: crossplane-system
specTemplate:
  versioning: false
  cannedACL: private
  region: us-east-1
  localPermission: ReadWrite
  providerRef:
    name: example
    namespace: crossplane-system
  reclaimPolicy: Delete
