apiVersion: database.crossplane.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: gitlab-postgresql
  namespace: default
spec:
  classRef:
    name: standard-aws-postgres
    namespace: crossplane-system
  writeConnectionSecretToRef:
    name: gitlab-postgresql
  engineVersion: "9.6"
