apiVersion: cache.crossplane.io/v1alpha1
kind: RedisCluster
metadata:
  name: gitlab-redis
  namespace: default
spec:
  classRef:
    name: standard-aws-redis
    namespace: crossplane-system
  writeConnectionSecretToRef:
    name: gitlab-redis
  engineVersion: "3.2"
