apiVersion: database.aws.conductor.io/v1alpha1
kind: RDSInstance
metadata:
  name: demo-rds
spec:
  class: db.t2.small
  connectionSecretRef:
    name: demo-rds-connection
  engine: mysql
  masterUsername: masteruser
  providerRef:
    name: demo-aws-provider
  securityGroups:
#  - vpc-default-sg - default security group for your VPC
#  - vpc-rds-sg - security group to allow RDS connection
  size: 20
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.6.1-apache
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: test-conn
              key: Endpoint
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: test-conn
              key: Username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-conn
              key: Password
        ports:
        - containerPort: 80
          name: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer