apiVersion: cache.crossplane.io/v1alpha1
kind: RedisCluster
metadata:
  name: gitlab-redis
  namespace: default
spec:
  classReference:
    name: standard-gcp-redis
    namespace: crossplane-system
  writeConnectionSecretTo:
    name: gitlab-redis
  engineVersion: "3.2"
