apiVersion: storage.gcp.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: demo-bucket
  namespace: crossplane-system
spec:
  labels:
    provisioner: crossplane
  location: ASIA
  nameFormat: demo-bucket-%s
  providerRef:
    name: demo-gcp
  reclaimPolicy: Delete
  requesterPays: true
  storageClass: MULTI_REGIONAL
