# Example GCP Bucket resource claim using the gcp-bucket resource class
apiVersion: storage.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: gitlab-lfs
spec:
  writeConnectionSecretToRef:
    name: gitlab-lfs
  name: gitlab-demo-lfs-%s
