# Example GCP Bucket resource claim using the gcp-bucket resource class
apiVersion: storage.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: gitlab-registry
spec:
  writeConnectionSecretToRef:
    name: gitlab-registry
  name: gitlab-demo-registry-%s
