# Example GCP Bucket resource claim using the gcp-bucket resource class
apiVersion: storage.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: gitlab-uploads
spec:
  writeConnectionSecretToRef:
    name: gitlab-uploads
  name: gitlab-demo-uploads-%s
