---
apiVersion: network.aws.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: rc-subnet1
  namespace: aws-connectivity
spec:
  cidrBlock: 192.168.64.0/18
  vpcId: ((VPC_ID))
  availabilityZone: ((AWS_REGION))a
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
    namespace: crossplane-system
---
apiVersion: network.aws.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: rc-subnet2
  namespace: aws-connectivity
spec:
  cidrBlock: 192.168.128.0/18
  vpcId: ((VPC_ID))
  availabilityZone: ((AWS_REGION))b
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
    namespace: crossplane-system
---
apiVersion: network.aws.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: rc-subnet3
  namespace: aws-connectivity
spec:
  cidrBlock: 192.168.192.0/18
  vpcId: ((VPC_ID))
  availabilityZone: ((AWS_REGION))c
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
    namespace: crossplane-system
