---
apiVersion: v1
data:
  credentials: BASE64ENCODED_AWS_PROVIDER_CREDS
kind: Secret
metadata:
  name: aws-provider-creds
  namespace: crossplane-system
type: Opaque
---
apiVersion: aws.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: aws-provider
  namespace: crossplane-system
spec:
  credentialsSecretRef:
    key: credentials
    name: aws-provider-creds
  region: REGION
---
apiVersion: database.aws.crossplane.io/v1alpha1
kind: RDSInstanceClass
metadata:
  name: standard-mysql
  namespace: crossplane-system
specTemplate:
  class: db.t2.small
  masterUsername: masteruser
  securityGroups:
   - RDS_SECURITY_GROUP # sg-1
  subnetGroupName: RDS_SUBNET_GROUP_NAME # eks-db-subnets
  size: 20
  engine: mysql
  providerRef:
    name: aws-provider
    namespace: crossplane-system
  reclaimPolicy: Delete
---
apiVersion: compute.aws.crossplane.io/v1alpha1
kind: EKSClusterClass
metadata:
  name: standard-cluster
  namespace: crossplane-system
specTemplate:
  region: REGION
  roleARN: EKS_ROLE_ARN # arn:aws:iam::<account-id>:role/<role-name>
  vpcId: EKS_VPC #vpc-01
  subnetIds:
   - EKS_SUBNET_ONE #subnet-01
   - EKS_SUBNET_TWO #subnet-02
   - EKS_SUBNET_THREE #subnet-03
  securityGroupIds:
   - EKS_SECURITY_GROUP #sg-01
  workerNodes:
    keyName: EKS_WORKER_KEY_NAME #named ec2 keypair
    nodeInstanceType: m3.medium
    nodeAutoScalingGroupMinSize: 1
    nodeAutoScalingGroupMaxSize: 1
    nodeGroupName: demo-nodes
    clusterControlPlaneSecurityGroup: EKS_SECURITY_GROUP #sg-01
  providerRef:
    name: aws-provider
    namespace: crossplane-system
  reclaimPolicy: Delete
---
