---
# AWS credentials secret
apiVersion: v1
data:
  credentials: BASE64ENCODED_AWS_PROVIDER_CREDS
kind: Secret
metadata:
  name: aws-creds
  namespace: crossplane-system
type: Opaque
---
# AWS provider that references the secrete credentials
apiVersion: aws.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: aws-provider
  namespace: crossplane-system
spec:
  credentialsSecretRef:
    key: credentials
    name: aws-creds
  region: us-east-1
