---
apiVersion: v1
kind: Namespace
metadata:
  name: app-project1-dev
---
apiVersion: database.crossplane.io/v1alpha1
kind: MySQLInstanceClass
metadata:
  name: standard-mysql
  namespace: app-project1-dev
  labels:
    default: "true"
classRef:
  kind: SQLServerClass
  apiVersion: database.azure.crossplane.io/v1alpha2
  name: azure-mysql-standard
  namespace: azure-infra-dev
---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesClusterClass
metadata:
  name: standard-cluster
  namespace: app-project1-dev
  labels:
    default: "true"
classRef:
  kind: AKSClusterClass
  apiVersion: compute.azure.crossplane.io/v1alpha2
  name: azure-aks-standard
  namespace: azure-infra-dev