---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: akscluster
spec:
  classRef:
    kind: AKSClusterClass
    apiVersion: compute.azure.crossplane.io/v1alpha1
    name: akscluster
    namespace: crossplane-system
  clusterVersion: "1.12"
  writeConnectionSecretToRef:
    name: akscluster
