---
apiVersion: compute.azure.crossplane.io/v1alpha2
kind: AKSClusterClass
metadata:
  name: akscluster
  namespace: crossplane-system
specTemplate:
  resourceGroupName: group-westus-1
  location: West US 2
  version: "1.12.8"
  nodeCount: 1
  nodeVMSize: Standard_B2s
  dnsNamePrefix: crossplane-aks
  disableRBAC: false
  writeServicePrincipalTo:
    name: akscluster
  providerRef:
    name: example
    namespace: crossplane-system
  reclaimPolicy: Delete
