apiVersion: compute.aws.crossplane.io/v1alpha1
kind: EKSCluster
metadata:
  name: demo-cluster
spec:
  region: us-east-1
  roleARN: # arn:aws:iam::<account-id>:role/<role-name>
  vpcId: #vpc-01
  subnetIds:
  #- subnet-01
  #- subnet-02
  #- subnet-03
  securityGroupIds:
    #- sg-01
  workerNodes:
    keyName: #named ec2 keypair
    nodeInstanceType: m3.medium
    nodeGroupName: demo-nodes
    clusterControlPlaneSecurityGroup: #sg-01
  providerRef:
    name: demo-aws-provider
  reclaimPolicy: Delete
