apiVersion: v1
data:
  credentials: BASE64ENCODED_AWS_PROVIDER_CREDS
kind: Secret
metadata:
  name: demo-aws-creds
  namespace: crossplane-system
type: Opaque
---
apiVersion: aws.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: demo-aws-provider
  namespace: crossplane-system
spec:
  credentialsSecretRef:
    key: credentials
    name: demo-aws-creds
  region: us-east-1
