apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
type: Opaque
data:
  rdsPassword: cGFzc3dvcmRvcnNvbWV0aGluZw==
---
apiVersion: database.aws.conductor.io/v1alpha1
kind: RDSInstance
metadata:
  name: rdssample
spec:
  class: db.t2.small # type of the db instance
  engine: postgres # what engine to use postgres, mysql, aurora-postgresql etc.
  masterUsername: postgres # Database username
  masterPasswordSecretRef: # reference to secret that contains database master password
    name: rds-secret # the name of the secret
    key: rdsPassword # the name of the key in the secret data that contains the password
  size: 10 # size in GB of underlying storage volume
  storagetype: gp2 # type of the underlying storage
  backupretentionperiod: 10 # days to keep backup, 0 means diable
  encrypted: true # should the database be encrypted
  #iops: 1000 # number of iops
  multiaz: true # multi AZ support
