# ResourceClass that defines the blueprint for how a "standard" CloudSQL instance
# should be dynamically provisioned
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: standard-gcp-postgres
  namespace: crossplane-system
  labels:
    resource: postgresqlinstance.storage.crossplane.io/v1alpha1
parameters:
  tier: db-custom-1-3840
  region: us-west2
  storageType: PD_SSD
  storageGB: "10"
provisioner: cloudsqlinstance.database.gcp.crossplane.io/v1alpha1
providerRef:
  name: demo-gcp
reclaimPolicy: Delete