---
apiVersion: compute.gcp.crossplane.io/v1alpha2
kind: GKEClusterClass
metadata:
  name: gkecluster
  namespace: crossplane-system
specTemplate:
  machineType: n1-standard-1
  numNodes: 1
  zone: us-central1-b
  providerRef:
    name: example
    namespace: crossplane-system
  reclaimPolicy: Delete
