---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: gkecluster
  labels:
    app: wordpress-demo
spec:
  classRef:
    kind: GKEClusterClass
    apiVersion: compute.gcp.crossplane.io/v1alpha2
    name: gkecluster
    namespace: crossplane-system
  writeConnectionSecretToRef:
    name: gkecluster
