---
# Azure Admin service principal secret - used by Azure Provider
apiVersion: v1
kind: Secret
metadata:
  name: azure-provider-creds
  namespace: crossplane-system
type: Opaque
data:
  credentials: BASE64ENCODED_AZURE_PROVIDER_CREDS
---
# Azure Provider with service principal secret reference - used to provision sql resources
apiVersion: azure.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: azure-sql-provider
  namespace: crossplane-system
spec:
  credentialsSecretRef:
    name: azure-provider-creds
    key: credentials
