---
# ResourceClass that defines the blueprint for how a "standard" Azure PostgreSQL Server
# should be dynamically provisioned
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: cloud-postgresql
  namespace: crossplane-system
parameters:
  adminLoginName: myadmin
  resourceGroupName: group-westus-1
  location: West US
  sslEnforced: "false"
  tier: Basic
  vcores: "1"
  family: Gen5
  storageGB: "25"
  backupRetentionDays: "7"
  geoRedundantBackup: "false"
provisioner: postgresqlserver.database.azure.crossplane.io/v1alpha1
providerRef:
  name: azure-sql-provider
reclaimPolicy: Delete
