# Example aws Bucket resource claim using the aws-bucket resource class
apiVersion: storage.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: gitlab-backups-tmp
spec:
  writeConnectionSecretToRef:
    name: gitlab-backups-tmp
  name: gitlab-demo-backups-tmp-%s
