# Example aws Bucket resource claim using the aws-bucket resource class
apiVersion: storage.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: gitlab-uploads
  namespace: default
spec:
  classRef:
    name: standard-aws-bucket
    namespace: crossplane-system
  writeConnectionSecretToRef:
    name: gitlab-uploads
  name: gitlab-demo-uploads-%s
