---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: ekscluster
spec:
  classRef:
    kind: EKSClusterClass
    apiVersion: compute.aws.crossplane.io/v1alpha2
    name: ekscluster
    namespace: crossplane-system
  writeConnectionSecretToRef:
    name: ekscluster
