---
apiVersion: storage.azure.crossplane.io/v1alpha2
kind: AccountClass
metadata:
  name: storageaccount-standard
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  storageAccountName: example-storage
  resourceGroupName: group-westus-1
  storageAccountSpec:
    kind: Storage
    location: West US
    sku:
      name: Standard_LRS
      tier: Standard
    tags:
      application: crossplane
  providerRef:
    name: example
  reclaimPolicy: Delete
