# ResourceClass that defines the blueprint for how a "standard" Azure storage
# account should be dynamically provisioned
apiVersion: storage.azure.crossplane.io/v1alpha2
kind: AccountClass
metadata:
  name: storageaccount
  namespace: crossplane-system
specTemplate:
  storageAccountName: example-storage
  resourceGroupName: group-westus-1
  storageAccountSpec:
    kind: Storage
    location: West US
    sku:
      name: Standard_LRS
      tier: Standard
    tags:
      application: crossplane
  providerRef:
    name: example
    namespace: crossplane-system
  reclaimPolicy: Delete
