---
apiVersion: storage.azure.crossplane.io/v1alpha2
kind: ContainerClass
metadata:
  name: storagecontainer
  namespace: crossplane-system
specTemplate:
  # Azure containers read their credentials from an account. We reuse the
  # providerRef class field to specify which account to read.
  accountReference:
    name: storageaccount
  providerRef:
    name: storageaccount
  reclaimPolicy: Delete
