---
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstanceClass
metadata:
  name: standard-mysql
  annotations:
    resourceclass.crossplane.io/is-default-class: "true"
specTemplate:
  forProvider:
    dbInstanceClass: db.t2.small
    masterUsername: cool_user
    vpcSecurityGroupIds:
      - sample-rds-sg
    dbsubnetGroupNameRef:
      name: sample-dbsubnetgroup
    allocatedStorage: 20
    engine: mysql
  providerRef:
    name: aws-provider
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
