---
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: rdspostgresql
  namespace: crossplane-system
parameters:
  class: db.t2.small
  masterUsername: masteruser
  securityGroups: "sg-ab1cdefg,sg-05adsfkaj1ksdjak"
  size: "20"
provisioner: rdsinstance.database.aws.crossplane.io/v1alpha1
providerRef:
  name: example
  namespace: crossplane-system
reclaimPolicy: Delete
