apiVersion: v1
data:
  credentials: BASE64ENCODED_AWS_PROVIDER_CREDS
kind: Secret
metadata:
  name: demo-aws-creds
  namespace: crossplane-system
type: Opaque
---
apiVersion: aws.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: demo-aws-provider
  namespace: crossplane-system
spec:
  credentialsSecretRef:
    key: credentials
    name: demo-aws-creds
  region: us-east-1
---
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: standard-eks-cluster
  namespace: crossplane-system
parameters:
  region: us-west-2
  roleARN: # arn:aws:iam::<account-id>:role/<role-name>
  vpcId: #vpc-01
  subnetIds: #subnet-01,subnet-02,subnet-03
  securityGroupIds: #sg-01
  workerKeyName: #named ec2 keypair
  workerNodeInstanceType: m3.medium
  workerNodeGroupName: demo-nodes
  workerClusterControlPlaneSecurityGroup: #sg-01
provisioner: eksclusters.compute.aws.crossplane.io/v1alpha1
providerRef:
  name: demo-aws-provider
reclaimPolicy: Delete
---
