---
# GCP Admin service account secret - used by GCP Provider
apiVersion: v1
kind: Secret
metadata:
  name: gcp-provider-creds
type: Opaque
data:
  credentials.json: BASE64ENCODED_GCP_PROVIDER_CREDS
---
# GCP Provider with service account secret reference - used to provision sql resources
apiVersion: gcp.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: gcp-sql-provider
spec:
  credentialsSecretRef:
    name: gcp-provider-creds
    key: credentials.json
  projectID: long-disk-191221
  requiredPermissions:
  - cloudsql.admin
