---
# GCP SQL user service account - used by application cloudsql-proxy side car
# - list cloudsql intances
# - connect to a cloudsql instance
apiVersion: v1
kind: Secret
metadata:
  name: gcp-sql-creds
  namespace: demo
type: Opaque
data:
  credentials.json: base64encrytpeddata
---
apiVersion: database.gcp.conductor.io/v1alpha1
kind: CloudsqlInstance
metadata:
  labels:
  name: cloudsql-demo
spec:
  provider: gcp-sql-provider
  #TODO we need to add CloudqlInstance functionality to get credentials from a given GCP Provider

  tier: db-n1-standard-1
  region: us-west2
  databaseVersion: MYSQL_5_7
  storageType: PD_SSD

  databaseName: demo-database
  #TODO we need to add CloudsqlInstance functionality to provision a database with a given name

  databaseUserRef: database-user
  #TODO we need to add CloudsqlInstance functionality to provision a database user using given database-user secret reference

  databaseSecretName: demo-database-connection
  #TODO we need to add CloudsqlInstance functionality to generate a secret with database connection information:
  # - instance-name: autogenerated using metadata.name + random suffix
  # - database-name: from this CRD spec
  # - database-user: from the databaseUserRef secret reference
  # - database-password: same as the above

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy"]
        env:
        - name: INSTANCE
          valueFrom:
            secretKeyRef:
              name: demo-database-connection
              key: instance
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/cloudsql/credentials.json
      - name: wordpress
        image: wordpress:4.6.1-apache
        env:
        # managed posgresql environment variables
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1  # cloudsql-proxy sidecar
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: demo-database-connection
              key: name
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: demo-database-connection
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-database-connection
              key: password
        ports:
        - containerPort: 80
          name: wordpress
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: gcp-sql-creds
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer