apiVersion: network.aws.crossplane.io/v1alpha2
kind: SecurityGroup
metadata:
  name: ((CONFIG_NAME))-controlplane-sg
spec:
  vpcId: ((VPC_ID))
  groupName: ((CONFIG_NAME))-controlplane-sg
  description: Cluster communication with worker nodes
  reclaimPolicy: Delete
  providerRef:
    name: example
