---
apiVersion: network.aws.crossplane.io/v1alpha2
kind: Subnet
metadata:
  name: ((CONFIG_NAME))-subnet1
spec:
  cidrBlock: 192.168.64.0/18
  vpcId: ((VPC_ID))
  availabilityZone: ((AWS_REGION))a
  reclaimPolicy: Delete
  providerRef:
    name: example
---
apiVersion: network.aws.crossplane.io/v1alpha2
kind: Subnet
metadata:
  name: ((CONFIG_NAME))-subnet2
spec:
  cidrBlock: 192.168.128.0/18
  vpcId: ((VPC_ID))
  availabilityZone: ((AWS_REGION))b
  reclaimPolicy: Delete
  providerRef:
    name: example
---
apiVersion: network.aws.crossplane.io/v1alpha2
kind: Subnet
metadata:
  name: ((CONFIG_NAME))-subnet3
spec:
  cidrBlock: 192.168.192.0/18
  vpcId: ((VPC_ID))
  availabilityZone: ((AWS_REGION))c
  reclaimPolicy: Delete
  providerRef:
    name: example
